### ISSUE TITLE
Demo app not working

### ISSUE THREAD

**Issue by bnussey** [alexrainman/nativescript-carousel-view#10]
Whenever I try and run the demo app on Android or iOS I get the following error message:

`file:///app/app.js:2:8: JS ERROR Error: Could not find module './helpers'`

**Comment by alexrainman** [comment]
It seems my .gitignore "ignored" that file. Will upload later on. Anyway you can create the file using this tutorial: https://www.nativescript.org/blog/use-async-await-with-typescript-in-nativescript-today

You can also find it in tns-modules/nativescript-carousel-view folder.

Move it to app folder.

**Comment by bnussey** [comment]
Thats now working, thanks alex!

**Comment by alexrainman** [comment]
No problem.
