### ISSUE TITLE
Adding another touch gesture to slider-view does not work for Android

### ISSUE THREAD

**Issue by bnussey** [alexrainman/nativescript-carousel-view#11]
We have a use case where we need to have a tap event on the entire slide.
I've added this code to the demo and while it works with iOS, it does not work on Android:
```
slider-view.xml
<StackLayout loaded="onLoaded" horizontalAlignment="center" padding="12" backgroundColor="yellow" tap="onTap" width="100%" height="100%">
    <Label text="{{ first }}" css="label"/>
    <Label text="{{ last }}"/>
    <Button text="Remove me" tap="buttonTap"/>
</StackLayout>

slider-view.ts
export function onTap(args: EventData) {
    console.log("Hello World!" + Math.random());
}
```

**Comment by bnussey** [comment]
Similar issue to https://github.com/TheOriginalJosh/nativescript-slides/issues/46 but in this case it still allows the slide to pan but the touch gesture is not registered.

**Comment by alexrainman** [comment]
I think i found the issue.

**Comment by alexrainman** [comment]
Releasing the fix.

**Comment by bnussey** [comment]
Awesome thanks Alex!
