### ISSUE TITLE
Indicators don't show on iOS until you swipe

### ISSUE THREAD

**Issue by sitefinitysteve** [alexrainman/nativescript-carousel-view#15]
First off... AWESOME job on this plugin

On iOS though it seems there are no indicators when the app loads, but when you START to swipe they pop in.

Video:
https://www.screencast.com/t/1kb3JwluwAup

**Comment by sitefinitysteve** [comment]
Sorry, had an idea of what the prob might be on the way in to work :)

The demo uses local data, my sample was using remote data .push (ed) onto the array in the NavigatingTo method... likely that's the problem?

**Comment by alexrainman** [comment]
In the case of remote data, please wait for the response and then assign items source. That will fix the problem. Also, i have a functionality named DragToLoad that will be the one to use in cases like yours.

**Comment by alexrainman** [comment]
I am releasing version 3 this week which supports empty array as source of the carousel. That will help.

**Comment by sitefinitysteve** [comment]
Thx mate, lets close this then :) 👍

**Comment by sitefinitysteve** [comment]
Could I just implant this in your head during testing :)  I mean you might already know and v3 will fix, but...

There's issued with Livesync as well.  So if I change my .js, no problems, everything reloads.  If I change something in the css or xml though this line
https://github.com/alexrainman/nativescript-carousel-view/blob/master/carousel-view.ios.ts#L321

Ends up having a source count of 0, even though I can see the model updating properly (though debug statements)
