### ISSUE TITLE
Generate third party library definitions

### ISSUE THREAD

**Issue by alexrainman** [alexrainman/nativescript-carousel-view#4]
@bradmartin i am including a third party library with gradle like this

```
dependencies {
  compile 'me.relex:circleindicator:1.2.2@aar'
}
```

But i cannot access the library from TypeScript. What i am missing? Do i need to generate the definitions? How?

**Comment by bradmartin** [comment]
I think there's a tool to generate the typings for native libs from
NativeScript. Ive never used it though.

**Comment by bradmartin** [comment]
Saw your issue on the repo. To bypass the compiler I'm sure you're aware of
casting to `any` but just wanted to check. I don't know where I read about
the tool to create ts defs from native libs. Ive just never used it so I
can find anything on it :/

**Comment by alexrainman** [comment]
Tried to cast to any but didnt work

**Comment by bradmartin** [comment]
Did you just try `declare var me: any;`? or `(<any>me...);` ?

**Comment by alexrainman** [comment]
@bradmartin i was able to translate CirclePageIndicator to TS and it works just fine. Just an small issue to solve and i am ready to release next version with indicators included :)

**Comment by bradmartin** [comment]
Very nice man. I haven't had much time to dive in and try it out lately :(
