### ISSUE TITLE
slide view loaded event not firing

### ISSUE THREAD

**Issue by terreb** [alexrainman/nativescript-carousel-view#5]
Slide view loaded event is not firing on iOS (probably on Android too, I've not tested)

nativescript 2.3.0          
tns-core-modules 2.3.0          
tns-ios 2.3.0
nativescript-carousel-view 2.0.1
simulator iOS 9.3

How to reproduce:

1. Add this snippet to app/Views/Slides/slider-view.ts in the demo app:

```typescript
export function onLoaded(args) {
    console.log('slide loaded')
}
```  

2. Make sure slider-view.xml exposes loaded event (should be there by default)

3. Run the demo on iOS

4. Tap on "Add Page" and see console messages

**Comment by alexrainman** [comment]
@terreb i am releasing a new version with a fix for this one. onLoaded() will be called, that will also will allow you to add gestures to labels.

**Comment by terreb** [comment]
3 days past since you closed the reported issue but it's still here in the latest version.

**Comment by alexrainman** [comment]
Theres no issue with the plugin. You must be doing something wrong on your end.

**Comment by terreb** [comment]
Ok, I got it. You are not going to fix the plugin of multiple issues, but rather give your ridiculous statements that someone doing something wrong. I don't know whether your employer punish you for not closed issues and you close them without checking or you want that community think that plugin is free of issues. But in any case your behaviour is more than weird.

**Comment by terreb** [comment]
onLoaded event is not fired, just fix this

**Comment by alexrainman** [comment]
Are you trying to bully me? Because if thats the case, you are getting completely wrong. This is something i do in my free time and im employee of no one in that case. So, stop being an smart ass and do something better with your life.

**Comment by terreb** [comment]
Just re-read your own comments here. You said "i am releasing a new version with a fix for this one. onLoaded() will be called, that will also will allow you to add gestures to label" agreeing that there is an issue with loading event and closed the issue without releasing it. Then I reminded that the issue is still here, loaded event is still not firing. Your comment "Theres no issue with the plugin. You must be doing something wrong on your end." Is not this weird? Same in another [issue](https://github.com/alexrainman/nativescript-carousel-view/issues/9) You first said there was no issues with my example and all was working for you, but then you said "Set orientation to horizontal (this doesnt work, i had same issue in xamarin)". In third issue:  This plugin is a really must-have for NativeScript and I'm actually trying to test it and reveal issues helping community and you to make it better, but you position is kind of strange.

**Comment by alexrainman** [comment]
I said i am releasing a fix for onLoaded and i will, i just wanted to ship another useful functionality with it: page indicators.

Yes, the fix for onLoaded will allow you to add tap events programmatically to labels. Thats a workaround.

When i say horizontal stacklayout doesnt works and thats its also an issue with Xamarin version of the plugin i couldnt solve, i am offering a workaround if you use a grid instead.

Theres nothing strange on that. Strange is you getting upset and trying to be bossy.

I am leaving 2 issues you reported opened because i cannot offer a workaround to them, particularly CSS not being applied. I believe its critical and it should be solved. I am working with {N} team in that one.

I will release a quick fix today for onLoaded().

Thanks.

**Comment by alexrainman** [comment]
I also believe this is a really useful plugin for the community and i am also trying to make it as stable and flexible as possible. Thanks.

**Comment by alexrainman** [comment]
Version 2.0.2 released. Now you can use onLoaded() to hook up tap event to labels.

https://docs.nativescript.org/cookbook/ui/gestures

**Comment by terreb** [comment]
Awesome, it works perfectly, thank you @alexrainman !
