### ISSUE TITLE
css not applying to slides

### ISSUE THREAD

**Issue by terreb** [alexrainman/nativescript-carousel-view#6]
nativescript 2.3.0
tns-core-modules 2.3.0
tns-ios 2.3.0
nativescript-carousel-view 2.0.1
simulator iOS 9.3

!!! Probably it's me doing something wrong if so please correct me. !!!

How to reproduce:

1. In demo app add any css classes to slider-view.xml
2. Add any styles to those classes to app.css
3. Run the app, see if styles are applied

I also tried to add slider-view.css with those styles to app/Views/Slides folder and change template-selector.ts as

```typescript
import { ITemplateSelector } from 'nativescript-carousel-view'
import { View } from 'ui/core/view'
import { topmost } from 'ui/frame'
import * as builder from 'ui/builder'

export class SlideTemplateSelector implements ITemplateSelector {
    
    OnSelectTemplate(position: number, bindingContext: any) {

        const page = topmost().currentPage

        let view = <View>builder.load({
            path: '~/components/order-online/choose-products/slides',
            name: 'slider-view',
            page: page
        })

        view.bindingContext = bindingContext

        return view
    }
}
```

...but nothing helped. Please advise.

**Comment by alexrainman** [comment]
@terreb i submitted a question to {N} team. CSS is being loaded but it's not being applied. Why? I don't know, yet :)

**Comment by alexrainman** [comment]
You can follow this https://github.com/NativeScript/NativeScript/issues/3054

**Comment by terreb** [comment]
Ok, awesome, thanks!

**Comment by alexrainman** [comment]
As a workaround, you can use inline CSS until we solve this issue.

https://docs.nativescript.org/ui/styling#inline-css

**Comment by alexrainman** [comment]
Solved!

**Comment by terreb** [comment]
Awesome, thanks a lot!
