### ISSUE TITLE
unable to get parent's property in xml

### ISSUE THREAD

**Issue by terreb** [alexrainman/nativescript-carousel-view#7]
nativescript 2.3.0
tns-core-modules 2.3.0
tns-ios 2.3.0
nativescript-carousel-view 2.0.1
simulator iOS 9.3

How to reproduce:

1. add this to slider-view.xml in the demo app:

```xml
    <Label text="{{ $parents['CarouselView'].position, $parents['CarouselView'].position }}" />
```

2. run the demo

**Comment by alexrainman** [comment]
@terreb i don't if you can access to $parents from a view loaded with builder. I will do my tests later on and let you know. Thanks

**Comment by alexrainman** [comment]
You can follow this https://github.com/NativeScript/NativeScript/issues/3077

**Comment by alexrainman** [comment]
{N} Team provided an example for this that i will be testing. Thanks

**Comment by alexrainman** [comment]
It seems that $parents doesn't provide access to the native widget properties but it's binding context instead, so if you want to access the CarouselView properties, you have to expose them in the ViewModel like this:

```
get position(): number {
   var page = frame.topmost().currentPage;
    var slider = <CarouselView>page.getViewById("carouselView");
    return slider.position;
}
```

**Comment by terreb** [comment]
ok, thanks
