### ISSUE TITLE
Tap not firing on label inside slide

### ISSUE THREAD

**Issue by terreb** [alexrainman/nativescript-carousel-view#8]
nativescript 2.3.0
tns-core-modules 2.3.0
tns-ios 2.3.0
nativescript-carousel-view 2.0.1
simulator iOS 9.3

How to reproduce:
1. Change slider-view.xml in the demo app to:

```xml
<StackLayout loaded="onLoaded" horizontalAlignment="center" padding="12">
    <Label text="{{ first }}"/> 
    <Label text="{{ last }}" tap="test"/>
    <Button text="Remove me" tap="buttonTap"/> 
</StackLayout>
```

2. Add handler to slider-view.ts

```typescript
export function test() {
    console.log('TEST')
}
```

3. Run the demo, tap on last name, see whether console prints 'TEST'

**Comment by alexrainman** [comment]
@terreb label doesn't have tap event. To attach events to label you have to use gestures http://docs.nativescript.org/api-reference/classes/_ui_label_.label.html

**Comment by alexrainman** [comment]
https://docs.nativescript.org/cookbook/ui/gestures

**Comment by terreb** [comment]
As you probably already found out by yourself tap event is working on labels outside your plugin. So, why the issue is closed?

**Comment by alexrainman** [comment]
Version 2.0.2 released. Now you can use onLoaded() to hook up tap event to labels.

https://docs.nativescript.org/cookbook/ui/gestures

**Comment by alexrainman** [comment]
Actually, closing this was the right thing. Label tap works both with a function in code behind and with bindings. Maybe fixing onLoaded() fixed that too? Thanks

**Comment by terreb** [comment]
I don't know, but it works like a charm now! Thanks a lot!
